SacramentMeetingPlannerFinished/Models/ErrorViewModel.cs
using System;

namespace SacramentMeetingPlanner.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SacramentMeetingPlannerFinished/Models/Sacrament.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SacramentMeetingPlanner.Models
{
    public class Sacrament
    {
        public int ID { get; set; }
        public string openSong { get; set; }
        public string closeSong { get; set; }
        public string conductor { get; set; }
        public string openPrayer { get; set; }
        public string closePrayer { get; set; }
        public string openSpeaker { get; set; }
        public string midSpeaker { get; set; }
        public string closeSpeaker { get; set; }
        public DateTime date { get; set; }

       //public ICollection<Enrollment> Enrollments { get; set; }
    }
}

SacramentMeetingPlannerFinished/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SacramentMeetingPlanner.Models;

namespace SacramentMeetingPlanner.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SacramentMeetingPlannerFinished/Controllers/SacramentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SacramentMeetingPlanner.Data;
using SacramentMeetingPlanner.Models;

namespace SacramentMeetingPlanner.Controllers
{
    public class SacramentsController : Controller
    {
        private readonly ChurchContext _context;

        public SacramentsController(ChurchContext context)
        {
            _context = context;
        }

        // GET: Sacraments
        public async Task<IActionResult> Index()
        {
            return View(await _context.Sacrament.ToListAsync());
        }

        // GET: Sacraments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sacrament = await _context.Sacrament
                .SingleOrDefaultAsync(m => m.ID == id);
            if (sacrament == null)
            {
                return NotFound();
            }

            return View(sacrament);
        }

        // GET: Sacraments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Sacraments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,openSong,closeSong,conductor,openPrayer,closePrayer,openSpeaker,midSpeaker,closeSpeaker,date")] Sacrament sacrament)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sacrament);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sacrament);
        }

        // GET: Sacraments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sacrament = await _context.Sacrament.SingleOrDefaultAsync(m => m.ID == id);
            if (sacrament == null)
            {
                return NotFound();
            }
            return View(sacrament);
        }

        // POST: Sacraments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,openSong,closeSong,conductor,openPrayer,closePrayer,openSpeaker,midSpeaker,closeSpeaker,date")] Sacrament sacrament)
        {
            if (id != sacrament.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sacrament);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SacramentExists(sacrament.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sacrament);
        }

        // GET: Sacraments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sacrament = await _context.Sacrament
                .SingleOrDefaultAsync(m => m.ID == id);
            if (sacrament == null)
            {
                return NotFound();
            }

            return View(sacrament);
        }

        // POST: Sacraments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sacrament = await _context.Sacrament.SingleOrDefaultAsync(m => m.ID == id);
            _context.Sacrament.Remove(sacrament);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SacramentExists(int id)
        {
            return _context.Sacrament.Any(e => e.ID == id);
        }
    }
}

SacramentMeetingPlannerFinished/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

SacramentMeetingPlannerFinished/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SacramentMeetingPlannerFinished/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="jumbotron">
    <h1>Sacrament Meeting Planner</h1>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Welcome to the Sacrament Meeting Planner</h2>
        <p>
            This tool is meant to streamline the process of planning for sacrament meetings.
        </p>
    </div>
</div>

SacramentMeetingPlannerFinished/Views/Sacraments/Create.cshtml
@model SacramentMeetingPlanner.Models.Sacrament

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Sacrament</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="openSong" class="control-label"></label>
                <input asp-for="openSong" class="form-control" />
                <span asp-validation-for="openSong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="closeSong" class="control-label"></label>
                <input asp-for="closeSong" class="form-control" />
                <span asp-validation-for="closeSong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="conductor" class="control-label"></label>
                <input asp-for="conductor" class="form-control" />
                <span asp-validation-for="conductor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="openPrayer" class="control-label"></label>
                <input asp-for="openPrayer" class="form-control" />
                <span asp-validation-for="openPrayer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="closePrayer" class="control-label"></label>
                <input asp-for="closePrayer" class="form-control" />
                <span asp-validation-for="closePrayer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="openSpeaker" class="control-label"></label>
                <input asp-for="openSpeaker" class="form-control" />
                <span asp-validation-for="openSpeaker" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="midSpeaker" class="control-label"></label>
                <input asp-for="midSpeaker" class="form-control" />
                <span asp-validation-for="midSpeaker" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="closeSpeaker" class="control-label"></label>
                <input asp-for="closeSpeaker" class="form-control" />
                <span asp-validation-for="closeSpeaker" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="date" class="control-label"></label>
                <input asp-for="date" class="form-control" />
                <span asp-validation-for="date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SacramentMeetingPlannerFinished/Views/Sacraments/Delete.cshtml
@model SacramentMeetingPlanner.Models.Sacrament

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sacrament</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.openSong)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.openSong)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.closeSong)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.closeSong)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.conductor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.conductor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.openPrayer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.openPrayer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.closePrayer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.closePrayer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.openSpeaker)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.openSpeaker)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.midSpeaker)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.midSpeaker)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.closeSpeaker)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.closeSpeaker)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SacramentMeetingPlannerFinished/Views/Sacraments/Details.cshtml
@model SacramentMeetingPlanner.Models.Sacrament

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Sacrament</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.openSong)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.openSong)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.closeSong)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.closeSong)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.conductor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.conductor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.openPrayer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.openPrayer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.closePrayer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.closePrayer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.openSpeaker)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.openSpeaker)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.midSpeaker)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.midSpeaker)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.closeSpeaker)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.closeSpeaker)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SacramentMeetingPlannerFinished/Views/Sacraments/Edit.cshtml
@model SacramentMeetingPlanner.Models.Sacrament

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Sacrament</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <p>Openning Song</p>
                <input asp-for="openSong" class="form-control" />
                <span asp-validation-for="openSong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <p>Closing Song</p>
                <input asp-for="closeSong" class="form-control" />
                <span asp-validation-for="closeSong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <p>Conductor</p>
                <input asp-for="conductor" class="form-control" />
                <span asp-validation-for="conductor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <p>Openning Prayer</p>
                <input asp-for="openPrayer" class="form-control" />
                <span asp-validation-for="openPrayer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <p>Closing Prayer</p>
                <input asp-for="closePrayer" class="form-control" />
                <span asp-validation-for="closePrayer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <p>Openning Speaker</p>
                <input asp-for="openSpeaker" class="form-control" />
                <span asp-validation-for="openSpeaker" class="text-danger"></span>
            </div>
            <div class="form-group">
                <p>Middle Speaker</p>
                <input asp-for="midSpeaker" class="form-control" />
                <span asp-validation-for="midSpeaker" class="text-danger"></span>
            </div>
            <div class="form-group">
                <p>Closing Speaker</p>
                <input asp-for="closeSpeaker" class="form-control" />
                <span asp-validation-for="closeSpeaker" class="text-danger"></span>
            </div>
            <div class="form-group">
                <p>Date</p>
                <input asp-for="date" class="form-control" />
                <span asp-validation-for="date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SacramentMeetingPlannerFinished/Views/Sacraments/Index.cshtml
@model IEnumerable<SacramentMeetingPlanner.Models.Sacrament>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    Openning Song
                </th>
                <th>
                    Closing Song
                </th>
                <th>
                    Conductor
                </th>

                <th>
                    Openning Prayer
                </th>

                <th>
                    Closing Prayer
                </th>
                <th>
                    Openning Speaker
                </th>
                <th>
                    Middle Speaker
                </th>
                <th>
                    Closing Speaker
                </th>
                <th>
                    Date
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.openSong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.closeSong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.conductor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.openPrayer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.closePrayer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.openSpeaker)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.midSpeaker)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.closeSpeaker)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.date)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

SacramentMeetingPlannerFinished/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sacrament Meeting Planner</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>


<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Sacrament Meeting Planner</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>*@
                    <li><a asp-area="" asp-controller="Sacraments" asp-action="Index">Sacrament Planner</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Sacrament Meeting Planner</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>